// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/me/Projects/Tunnel/React_Ant_Design_Pro/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/home/me/Projects/Tunnel/React_Ant_Design_Pro/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import AreaChartOutlined from '/home/me/Projects/Tunnel/React_Ant_Design_Pro/node_modules/@ant-design/icons/es/icons/AreaChartOutlined';
import DesktopOutlined from '/home/me/Projects/Tunnel/React_Ant_Design_Pro/node_modules/@ant-design/icons/es/icons/DesktopOutlined';
export default { SmileOutlined, CrownOutlined, AreaChartOutlined, DesktopOutlined };
